#!/bin/sh

cari(){  printf "%i"     "'$1"; }
carin(){ printf "%i\012" "'$1"; }
carx(){  printf "%x"     "'$1"; }
carxn(){ printf "%x\012" "'$1"; }
cadi(){  printf "$1"     | hexdump -v -e '1/1 "%i "'; }
cadin(){ printf "$1\012" | hexdump -v -e '1/1 "%i "'; }
cadx(){  printf "$1"     | hexdump -v -e '1/1 "%x "'; }
cadxn(){ printf "$1\012" | hexdump -v -e '1/1 "%x "'; }
