#!/bin/sh

echo $@

consalto(){
	echo ""
	if [[ "$2" == "ev" ]];then
		eval "$1"
	else
		echo "$1"
	fi
}
cantidad_lineas(){
	if [[ "$(printf "%s" "$1" | wc -w)" == "0" ]];then
		devuelve="0"
	else
		devuelve="$(($(printf "%s" "$1" | wc -l)+1))"
	fi
	echo "$devuelve"
}
seleccionar(){
	echo "$1" | head -n "$2" | tail -n 1
}

h="User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Goanna/4.0 Firefox/55.0 Basilisk/20180202"
i="curl -s -H \"$h\" \"https://pkgs.org/search/?q=$1\""
a=$(eval $i)

j="slackware debian"  | tr " " "\n"

if [[ "$a" == "" ]];then
	echo "Error de internet"
	exit
fi

if [[ "$(echo $a | grep "<title>Error 403: Forbidden</title>")" != "" ]];then
	echo "Error 403"
	exit
fi

b="$(echo "$a" | grep -Pi "http.+html" | grep -Po '"http.*"' | sed 's/["]//g' \
| grep -vi arm64 | grep -vi aarch64 | grep -vi i686 | grep -vi i586
)"

b2="$(echo "$b" | grep $($j).pkgs.org)"
b22="$(echo "$b" | grep debian.pkgs.org)"
b23="$(echo "$b" | grep -v debian.pkgs.org)"

if [[ "$2" == "noslackware" && "$b2" != "" && "$b22" != "" ]];then
	b="$(echo "$b" | grep -v slackware.pkgs.org)"
fi

if [[ "$b22" != "" && "$b23" == "" ]];then
	b32="$(echo "$b" | grep -o "/[.a-z0-9]*")"
	b4="$(seleccionar "$b32" 3)"
	b5="$(echo "$b" | grep "$b4")"
fi

if [[ "$b5" != "" ]];then
	b="$b5"
fi

b6="$(cantidad_lineas "$b")"

if [[ "$b6" == "0" ]];then
	echo "No hay para elegir."
elif [[ "$b6" == "1" ]];then
		d="$b"
else
	echo "$b" | grep -n ""
	read c
	d=$(echo "$b" | head -n $c | tail -n 1)
fi

consalto "URL elegida: $d"
d2="curl -s -H \"$h\" $d"
e=$(eval $d2)

f=$(echo "$e" | grep -Pi "td.*text-break.*http" | grep -Po 'http[^<]*' | tail -n 1)
consalto "Servidor oficial: "
echo "$f"

g=$(basename $f)

consalto "curl $f --output $g" ev

consalto "$g"
consalto "xdg-open $g" ev
