#!/bin/sh

echo "$@"

a="aries"
b="$($1 2>&1 | grep $a)"
shift
if [[ "$b" != "" ]];then
        c="$(echo "$b" | sed -r "s/.*$a: //g"  | sed -r "s/:.*//g")"
        _curlpkgsorg "$c" $@
else
        echo "El programa ya está arreglado."
fi
